# -*- coding: utf-8 -*-
"""NLP Tasks Using Transformers and Piplines.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aaLscL-L7-mja0_Ig5hpTpABECC4ALjT
"""

#Install Transformers
!pip install transformers

#Import Pipeline for Sentiment analysis
from transformers import pipeline
classifier = pipeline("sentiment-analysis")
classifier("This is the worst day of my life")

#Sentiment Analysis for Two or More Sentences
classifier(
    ['this product is good but not satisfaction', 'good day', 'bad day', "very poor"]
)

#Named Entity Recognition Using Pipeline
ner_pipeline = pipeline("ner", grouped_entities=True)
result = ner_pipeline("Barack Obama was born in Hawaii.")
print(result)

#Zero-Shot-Classification using pipeline
classifier1 = pipeline("zero-shot-classification")
classifier1(
    "I am Working on new project",
    candidate_labels = ["AI", "Frontend", "backend"]
)

#Text Generation using Pipeline
generator = pipeline("text-generation", model="gpt2-medium")
generator("APJ most commonly refers to Avul Pakir Jainulabdeen Abdul Kalam, the 11th President")

#Question and Answering
qa = pipeline("question-answering")
context = "Dr APJ abdul kalam – India NCC APJ most commonly refers to Avul Pakir Jainulabdeen Abdul Kalam, the 11th President of India and a renowned aerospace engineer. He was also known as the Missile Man of India and the People's President. Besides his political role, he was a scientist and played a key part in India's space and missile programs ."

answer = qa(question = "Who was APJ Abdul Kalam?", context =context)
print(answer)

#Find Missing Word
missing = pipeline("fill-mask", model="bert-base-uncased")
result = missing("[MASK] is the owner?")
print(result)

#English to French Translation
translator = pipeline("translation_en_to_fr")
result = translator("Hello, how are you?", max_length=40)
print(result[0]['translation_text'])